import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
    title: "S-Shopping-Wishlist",
    description: "Generated by create next app",
};

const WishlistLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <>
            {children}
        </>
    )
}

export default WishlistLayout
